services:
  easymq:
    image: ghcr.io/muhammad-sho/easymq:latest
    container_name: easymq
    hostname: easymq
    restart: unless-stopped
    ports:
      - "3000:3000"

  redis:
    image: redis:7-alpine
    container_name: easymq-redis
    hostname: easymq-redis
    restart: unless-stopped
    volumes:
      - ./data/redis:/data
